import ProtectedPage from "../components/ProtectedPage";
import {
  AddResourcePage,
  BrowsePage,
  CollectionsPage,
  ContributorProfilePage,
  ExamFeedbackPage,
  ExplorePage,
  FlashcardModePage,
  GuideEditorPage,
  GuideReaderPage,
  GuidesListPage,
  LmsHomePage,
  MyContributionsPage,
  ProgressPage as LmsProgressPage,
  PYQBankPage,
  QuestionBankPage,
  QuizModePage,
  RequestBoardPage,
  ResourceDetailPage,
  RevisionQueuePage,
  RoadmapBuilderPage,
  RoadmapViewerPage,
  RoadmapsListPage,
  SavedResourcesPage,
  SubjectOverviewPage,
} from "../pages/LMS";

export const lmsRoutes = [
  { path: "/resources", element: <ProtectedPage><LmsHomePage /></ProtectedPage> },
  { path: "/resources/browse", element: <ProtectedPage><BrowsePage /></ProtectedPage> },
  { path: "/resources/explore", element: <ProtectedPage><ExplorePage /></ProtectedPage> },
  { path: "/resources/add", element: <ProtectedPage><AddResourcePage /></ProtectedPage> },
  { path: "/resources/contributors/:userId", element: <ProtectedPage><ContributorProfilePage /></ProtectedPage> },
  { path: "/resources/:id", element: <ProtectedPage><ResourceDetailPage /></ProtectedPage> },
  { path: "/resources/subject/:code", element: <ProtectedPage><SubjectOverviewPage /></ProtectedPage> },
  { path: "/resources/subject/:code/pyq", element: <ProtectedPage><PYQBankPage /></ProtectedPage> },
  { path: "/resources/guides", element: <ProtectedPage><GuidesListPage /></ProtectedPage> },
  { path: "/resources/guides/new", element: <ProtectedPage><GuideEditorPage /></ProtectedPage> },
  { path: "/resources/guides/:id", element: <ProtectedPage><GuideReaderPage /></ProtectedPage> },
  { path: "/resources/roadmaps", element: <ProtectedPage><RoadmapsListPage /></ProtectedPage> },
  { path: "/resources/roadmaps/new", element: <ProtectedPage><RoadmapBuilderPage /></ProtectedPage> },
  { path: "/resources/roadmaps/:id", element: <ProtectedPage><RoadmapViewerPage /></ProtectedPage> },
  { path: "/resources/quiz/:id", element: <ProtectedPage><QuizModePage /></ProtectedPage> },
  { path: "/resources/flashcards/:id", element: <ProtectedPage><FlashcardModePage /></ProtectedPage> },
  { path: "/resources/question-bank", element: <ProtectedPage><QuestionBankPage /></ProtectedPage> },
  { path: "/resources/requests", element: <ProtectedPage><RequestBoardPage /></ProtectedPage> },
  { path: "/resources/me/contributions", element: <ProtectedPage><MyContributionsPage /></ProtectedPage> },
  { path: "/resources/me/bookmarks", element: <ProtectedPage><SavedResourcesPage /></ProtectedPage> },
  { path: "/resources/me/collections", element: <ProtectedPage><CollectionsPage /></ProtectedPage> },
  { path: "/resources/me/progress", element: <ProtectedPage><LmsProgressPage /></ProtectedPage> },
  { path: "/resources/me/revision", element: <ProtectedPage><RevisionQueuePage /></ProtectedPage> },
  { path: "/resources/me/exam-feedback", element: <ProtectedPage><ExamFeedbackPage /></ProtectedPage> },
];
