name: university-erp-data

services:
  redis:
    image: redis:7-alpine
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - erp_data

networks:
  erp_data:
    name: erp_data

volumes:
  redis_data:
