import type {
  ResourceCatalogCourse,
  ResourceCatalogResponse,
  ResourceSubjectResponse,
  LearningResourceItem,
  ResourceLibraryResponse,
  ResourceRecommendation,
  ContentWorkflowSpec,
  ContentHistoryEntry,
  ContentBulkPreview,
  UploadedResource,
  LmsTrackerSnapshotSummary,
  LmsTrackerRecommendationEvent,
  CareerReadiness,
  UnifiedInsights,
  LmsPagination,
  LmsTopic,
  LmsComment,
  LmsAnnotation,
  LmsPublisherSummary,
  LmsModerationSummary,
  LmsRecommendationReason,
  LmsResourceFlag,
  LmsModerationAuditEntry,
  LmsResource,
  LmsGuideSection,
  LmsGuide,
  LmsRoadmapNode,
  LmsRoadmap,
  LmsRequest,
  LmsCollection,
  LmsModerationQueueResponse
} from "./types";

export const STATIC_LMS_PUBLISHER: LmsPublisherSummary = {
  userId: "AP23110010234",
  displayName: "AP23110010234",
  contributionCount: 12,
  approvedCount: 11,
  flaggedCount: 1,
  hiddenCount: 0,
  qualityAverage: 8.4,
  upvoteTotal: 86,
  trustScore: 91,
  lastPublishedAt: "2026-05-23T08:10:00.000Z",
};

export const STATIC_LMS_RESOURCES: LmsResource[] = [
  {
    id: "lms-res-indexing",
    type: "note",
    title: "Database indexing guide",
    description: "A compact guide to index selection, query plans, and common exam patterns.",
    difficulty: "intermediate",
    semester: "6",
    subjectCode: "CSE301",
    subjectName: "Database Systems",
    unit: "Query Optimization",
    unitNormalized: "query-optimization",
    tags: ["indexes", "sql", "query-plans"],
    uploadedBy: STATIC_LMS_PUBLISHER.userId,
    uploadedAt: "2026-05-23T08:10:00.000Z",
    viewCount: 420,
    upvotes: 48,
    bookmarkCount: 31,
    commentCount: 6,
    qualityScore: 8.8,
    effectivenessScore: 3.7,
    examProvenScore: 2.9,
    estimatedMinutes: 12,
    renderType: "note",
    noteContent: "Use selective indexes and verify plans before optimizing.",
    moderationState: 0,
    flagCount: 0,
    publisher: STATIC_LMS_PUBLISHER,
    moderation: {
      state: 0,
      label: "Clear",
      flagCount: 0,
      publicEligible: true,
      searchEligible: true,
      recommendationEligible: true,
      needsReview: false,
    },
    confidence: 0.86,
    recommendationScore: 0.74,
    reasons: [
      { code: "subjectMatch", label: "Matches your subject focus", weight: 1 },
      { code: "engagementScore", label: "High community engagement", weight: 0.82 },
      { code: "qualityScore", label: "Strong learner quality signals", weight: 0.88 },
    ],
    inputsUsed: {
      algorithmKey: "ranking-v2",
      factors: { subjectMatch: 1, engagementScore: 0.82, qualityScore: 0.88 },
      moderationState: 0,
      flagCount: 0,
      publisherTrustScore: STATIC_LMS_PUBLISHER.trustScore,
    },
    rankingPolicy: {
      algorithmKey: "ranking-v2",
      eligible: true,
      filters: ["not_deleted", "moderation_clear", "no_open_flags"],
    },
    topics: [{ id: "topic-indexes", label: "Indexes", subjectCode: "CSE301" }],
  },
  {
    id: "lms-res-normalization",
    type: "note",
    title: "Normalization checklist",
    description: "A student-contributed checklist for decompositions and normal forms.",
    difficulty: "beginner",
    semester: "6",
    subjectCode: "CSE301",
    subjectName: "Database Systems",
    unit: "Normalization",
    unitNormalized: "normalization",
    tags: ["normalization", "dbms"],
    uploadedBy: "AP23110010555",
    uploadedAt: "2026-05-20T09:30:00.000Z",
    viewCount: 128,
    upvotes: 11,
    bookmarkCount: 8,
    commentCount: 2,
    qualityScore: 5.9,
    effectivenessScore: 1.6,
    examProvenScore: 1.2,
    estimatedMinutes: 8,
    moderationState: 1,
    flagCount: 1,
    flagReason: "Needs citation review",
    publisher: {
      userId: "AP23110010555",
      displayName: "AP23110010555",
      contributionCount: 3,
      approvedCount: 2,
      flaggedCount: 1,
      hiddenCount: 0,
      qualityAverage: 5.6,
      upvoteTotal: 19,
      trustScore: 64,
      lastPublishedAt: "2026-05-20T09:30:00.000Z",
    },
    moderation: {
      state: 1,
      label: "Flagged for review",
      flagCount: 1,
      flagReason: "Needs citation review",
      publicEligible: true,
      searchEligible: true,
      recommendationEligible: false,
      needsReview: true,
    },
    flags: [
      {
        id: "flag-normalization-1",
        resourceId: "lms-res-normalization",
        userId: "AP23110010001",
        reason: "Needs citation review",
        status: "open",
        createdAt: "2026-05-25T08:00:00.000Z",
      },
    ],
    audit: [
      {
        id: "audit-normalization-1",
        resourceId: "lms-res-normalization",
        action: "reported",
        actorId: "AP23110010001",
        fromState: 0,
        toState: 1,
        reason: "Needs citation review",
        createdAt: "2026-05-25T08:00:00.000Z",
      },
    ],
    topics: [{ id: "topic-normalization", label: "Normalization", subjectCode: "CSE301" }],
  },
];
