import type { PageBlueprint } from "../erpBlueprintTypes";

export const CORE_PAGE_BLUEPRINTS: Record<string, PageBlueprint> = {

  "/dashboard": {
    route: "/dashboard",
    heading: "Dashboard",
    fetchKeys: ["dashboard"],
    domain: "erp",
    sourceMode: "erp",
    integrationState: "native",
    renderer: "dashboard",
    loadingMessage: "Loading dashboard...",
  },

  "/academic/timetable": {
    route: "/academic/timetable",
    heading: "Time Table",
    fetchKeys: ["academic/time-table"],
    domain: "erp",
    sourceMode: "erp",
    integrationState: "native",
    transform: "timetable",
    renderer: "timetable",
    loadingMessage: "Loading time table...",
  },
  "/academic/attendance-details": {
    route: "/academic/attendance-details",
    heading: "Attendance Details",
    fetchKeys: [
      "academic/attendance-details",
      "academic/od-ml-details",
      "academic/student-attendance",
    ],
    domain: "erp",
    sourceMode: "erp",
    integrationState: "native",
    renderer: "attendance",
    loadingMessage: "Loading attendance details...",
  },
  "/academic/curriculum": {
    route: "/academic/curriculum",
    heading: "Curriculum",
    fetchKeys: ["academic/student-wise-subjects"],
    domain: "erp",
    sourceMode: "erp",
    integrationState: "native",
    renderer: "curriculum",
    loadingMessage: "Loading curriculum...",
  },
  "/academic/sap-scholarships": {
    route: "/academic/sap-scholarships",
    heading: "SAP & Scholarships",
    fetchKeys: ["sap/attachments", "sap/details"],
    domain: "erp",
    sourceMode: "erp",
    integrationState: "native",
    renderer: "sap-scholarships",
    loadingMessage: "Loading SAP and scholarship details...",
  },

  "/exams/current-semester-results": {
    route: "/exams/current-semester-results",
    heading: "Current Semester Results",
    fetchKeys: [
      "examination/current-semester-results",
      "examination/internal-mark-details",
      "academic/course-registration",
      "academic/student-wise-subjects",
      "academic/cgpa-summary",
    ],
    domain: "erp",
    sourceMode: "erp",
    integrationState: "native",
    renderer: "results-current",
    loadingMessage: "Loading current semester results...",
  },
  "/exams/earlier-semester-results": {
    route: "/exams/earlier-semester-results",
    heading: "Earlier Semester Results",
    fetchKeys: ["examination/earlier-internal-marks", "examination/exam-mark-details"],
    domain: "erp",
    sourceMode: "erp",
    integrationState: "native",
    renderer: "results-earlier",
    loadingMessage: "Loading earlier semester results...",
  },
  "/exams/essentials": {
    route: "/exams/essentials",
    heading: "Exam Essentials",
    fetchKeys: ["exams/essentials"],
    domain: "erp",
    sourceMode: "external",
    integrationState: "summary",
    renderer: "generic",
    loadingMessage: "Loading exam essentials...",
  },

  "/finance/fee-dues": {
    route: "/finance/fee-dues",
    heading: "Fees Dues",
    fetchKeys: ["finance/fee-due-details"],
    domain: "erp",
    sourceMode: "erp",
    integrationState: "native",
    renderer: "finance-dues",
    loadingMessage: "Loading fee dues...",
  },
  "/finance/fee-paid": {
    route: "/finance/fee-paid",
    heading: "Fees Paid",
    fetchKeys: [
      "finance/fee-paid-details",
      "finance/payment-acknowledgment",
      "finance/online-payment-verification",
    ],
    domain: "erp",
    sourceMode: "erp",
    integrationState: "native",
    renderer: "finance-paid",
    loadingMessage: "Loading paid fees...",
  },
  "/finance/bank-details": {
    route: "/finance/bank-details",
    heading: "Bank Details",
    fetchKeys: ["finance/bank-account-details"],
    domain: "erp",
    sourceMode: "erp",
    integrationState: "native",
    renderer: "bank-details",
    loadingMessage: "Loading bank details...",
  },

  "/transport-hostel/room-details": {
    route: "/transport-hostel/room-details",
    heading: "Rooms Details",
    fetchKeys: ["hostel/room-details"],
    domain: "campus",
    sourceMode: "erp",
    integrationState: "native",
    renderer: "room-details",
    loadingMessage: "Loading room details...",
  },
  "/transport-hostel/route-details": {
    route: "/transport-hostel/route-details",
    heading: "Routes Details",
    fetchKeys: [],
    domain: "campus",
    integrationState: "placeholder",
    renderer: "generic",
    placeholderReason: "No university ERP source mapped.",
  },
  "/transport-hostel/faqs": {
    route: "/transport-hostel/faqs",
    heading: "FAQs",
    fetchKeys: ["hostel/hostel-layout-&-faqs", "transport/transport-&-faqs"],
    domain: "campus",
    sourceMode: "erp",
    integrationState: "native",
    renderer: "faqs",
    loadingMessage: "Loading FAQs...",
  },
  "/transport-hostel/refund-change-requests": {
    route: "/transport-hostel/refund-change-requests",
    heading: "Refund & Change Requests",
    fetchKeys: ["hostel/hostel-refund-policy", "transport/transport-refund-policy"],
    domain: "campus",
    sourceMode: "erp",
    integrationState: "native",
    renderer: "refund-change",
    loadingMessage: "Loading refund and change requests...",
  },
  "/transport-hostel/outing-maintenance": {
    route: "/transport-hostel/outing-maintenance",
    heading: "Outing & Maintenance",
    fetchKeys: [],
    domain: "campus",
    integrationState: "placeholder",
    renderer: "generic",
    placeholderReason: "No university ERP source mapped.",
  },

  "/registration/course-registration": {
    route: "/registration/course-registration",
    heading: "Course Registration",
    fetchKeys: ["academic/course-registration", "academic/course-registration-cancellation"],
    domain: "erp",
    sourceMode: "erp",
    integrationState: "native",
    renderer: "document",
    loadingMessage: "Loading course registration...",
  },
  "/registration/minor-oe-registration": {
    route: "/registration/minor-oe-registration",
    heading: "Minor / OE Registration",
    fetchKeys: ["academic/minor-program-registration"],
    domain: "erp",
    sourceMode: "erp",
    integrationState: "native",
    renderer: "document",
    loadingMessage: "Loading minor/OE registration...",
  },
  "/registration/events-registration": {
    route: "/registration/events-registration",
    heading: "Events Registration",
    fetchKeys: [],
    domain: "campus",
    sourceMode: "internal",
    integrationState: "native",
    renderer: "generic",
    loadingMessage: "Loading events registration...",
  },
  "/registration/exam-registration": {
    route: "/registration/exam-registration",
    heading: "Exam Registration",
    fetchKeys: ["examination/exam-registration", "examination/exam-registration-details"],
    domain: "erp",
    sourceMode: "erp",
    integrationState: "native",
    renderer: "document",
    loadingMessage: "Loading exam registration...",
  },
  "/registration/hostel-registration": {
    route: "/registration/hostel-registration",
    heading: "Hostel Registration",
    fetchKeys: ["hostel/hostel-booking-for-full-year"],
    domain: "campus",
    sourceMode: "erp",
    integrationState: "native",
    renderer: "document",
    loadingMessage: "Loading hostel registration...",
  },
  "/registration/transport-registration": {
    route: "/registration/transport-registration",
    heading: "Transport Registration",
    fetchKeys: ["transport/transport-registration", "transport/registration-acknowledgment"],
    domain: "campus",
    sourceMode: "erp",
    integrationState: "native",
    renderer: "document",
    loadingMessage: "Loading transport registration...",
  },
  "/registration/sap-registration": {
    route: "/registration/sap-registration",
    heading: "SAP Registration",
    fetchKeys: ["sap/sap-process"],
    domain: "erp",
    sourceMode: "erp",
    integrationState: "native",
    renderer: "document",
    loadingMessage: "Loading SAP registration...",
  },
  "/registration/registration-tracker": {
    route: "/registration/registration-tracker",
    heading: "Registration Tracker",
    fetchKeys: [],
    domain: "erp",
    integrationState: "placeholder",
    renderer: "generic",
    placeholderReason: "No university ERP source mapped.",
  },
};
