import type { PageBlueprint } from "../erpBlueprintTypes";

export const EVENT_PAGE_BLUEPRINTS: Record<string, PageBlueprint> = {
  "/events/attendance": {
    route: "/events/attendance",
    heading: "Event Attendance",
    fetchKeys: ["events/event-attendance"],
    domain: "erp",
    sourceMode: "erp",
    integrationState: "native",
    renderer: "generic",
    loadingMessage: "Loading event attendance...",
  },
  "/events": {
    route: "/events",
    heading: "Discover",
    fetchKeys: [],
    domain: "campus",
    sourceMode: "internal",
    integrationState: "native",
    renderer: "generic",
    loadingMessage: "Loading events...",
  },
  "/events/:eventId": {
    route: "/events/:eventId",
    heading: "Event Details",
    fetchKeys: [],
    domain: "campus",
    sourceMode: "internal",
    integrationState: "native",
    renderer: "generic",
    loadingMessage: "Loading event...",
  },
  "/events/my-activity": {
    route: "/events/my-activity",
    heading: "My Activity",
    fetchKeys: [],
    domain: "campus",
    sourceMode: "internal",
    integrationState: "native",
    renderer: "generic",
    loadingMessage: "Loading activity...",
  },
  "/events/my-created": {
    route: "/events/my-created",
    heading: "My Created Events",
    fetchKeys: [],
    domain: "campus",
    sourceMode: "internal",
    integrationState: "native",
    renderer: "generic",
    loadingMessage: "Loading created events...",
  },
  "/events/create": {
    route: "/events/create",
    heading: "Create Event",
    fetchKeys: [],
    domain: "campus",
    sourceMode: "internal",
    integrationState: "native",
    renderer: "generic",
    loadingMessage: "Loading event builder...",
  },

  "/events/my-teams": {
    route: "/events/my-teams",
    heading: "My Teams",
    fetchKeys: [],
    domain: "campus",
    sourceMode: "internal",
    integrationState: "native",
    renderer: "generic",
    loadingMessage: "Loading teams...",
  },
  "/events/:eventId/register": {
    route: "/events/:eventId/register",
    heading: "Register for Event",
    fetchKeys: [],
    domain: "campus",
    sourceMode: "internal",
    integrationState: "native",
    renderer: "generic",
    loadingMessage: "Loading registration...",
  },
  "/events/:eventId/teams/create": {
    route: "/events/:eventId/teams/create",
    heading: "Create Team",
    fetchKeys: [],
    domain: "campus",
    sourceMode: "internal",
    integrationState: "native",
    renderer: "generic",
    loadingMessage: "Loading team creation...",
  },
  "/events/:eventId/teams/:teamId": {
    route: "/events/:eventId/teams/:teamId",
    heading: "Team Details",
    fetchKeys: [],
    domain: "campus",
    sourceMode: "internal",
    integrationState: "native",
    renderer: "generic",
    loadingMessage: "Loading team...",
  },
  "/events/:eventId/certificate/:roundId": {
    route: "/events/:eventId/certificate/:roundId",
    heading: "Claim Certificate",
    fetchKeys: [],
    domain: "campus",
    sourceMode: "internal",
    integrationState: "native",
    renderer: "generic",
    loadingMessage: "Loading certificate...",
  },
  "/events/:eventId/leaderboard/:roundId": {
    route: "/events/:eventId/leaderboard/:roundId",
    heading: "Leaderboard",
    fetchKeys: [],
    domain: "campus",
    sourceMode: "internal",
    integrationState: "native",
    renderer: "generic",
    loadingMessage: "Loading leaderboard...",
  },
  "/events/:eventId/manage/roles": {
    route: "/events/:eventId/manage/roles",
    heading: "Manage Roles",
    fetchKeys: [],
    domain: "campus",
    sourceMode: "internal",
    integrationState: "native",
    renderer: "generic",
    loadingMessage: "Loading roles...",
  },
  "/events/:eventId/manage/certificate": {
    route: "/events/:eventId/manage/certificate",
    heading: "Certificate Template",
    fetchKeys: [],
    domain: "campus",
    sourceMode: "internal",
    integrationState: "native",
    renderer: "generic",
    loadingMessage: "Loading certificate template...",
  },
  "/events/:eventId/submit/:roundId": {
    route: "/events/:eventId/submit/:roundId",
    heading: "Submit Your Work",
    fetchKeys: [],
    domain: "campus",
    sourceMode: "internal",
    integrationState: "native",
    renderer: "generic",
    loadingMessage: "Loading round details...",
  },
  "/events/:eventId/my-results/:roundId": {
    route: "/events/:eventId/my-results/:roundId",
    heading: "Your Results",
    fetchKeys: [],
    domain: "campus",
    sourceMode: "internal",
    integrationState: "native",
    renderer: "generic",
    loadingMessage: "Loading your results...",
  },
  "/events/:eventId/manage": {
    route: "/events/:eventId/manage",
    heading: "Manage Competition",
    fetchKeys: [],
    domain: "campus",
    sourceMode: "internal",
    integrationState: "native",
    renderer: "generic",
    loadingMessage: "Loading competition data...",
  },
  "/events/:eventId/manage/rounds/:roundId/submissions": {
    route: "/events/:eventId/manage/rounds/:roundId/submissions",
    heading: "Submissions",
    fetchKeys: [],
    domain: "campus",
    sourceMode: "internal",
    integrationState: "native",
    renderer: "generic",
    loadingMessage: "Loading submissions...",
  },
  "/events/:eventId/manage/rounds/:roundId/submissions/:submissionId/evaluate": {
    route: "/events/:eventId/manage/rounds/:roundId/submissions/:submissionId/evaluate",
    heading: "Evaluate Submission",
    fetchKeys: [],
    domain: "campus",
    sourceMode: "internal",
    integrationState: "native",
    renderer: "generic",
    loadingMessage: "Loading submission...",
  },
  "/events/:eventId/manage/rounds/:roundId/shortlist": {
    route: "/events/:eventId/manage/rounds/:roundId/shortlist",
    heading: "Shortlist & Publish",
    fetchKeys: [],
    domain: "campus",
    sourceMode: "internal",
    integrationState: "native",
    renderer: "generic",
    loadingMessage: "Loading evaluation data...",
  },
  "/feedback/course-feedback": {
    route: "/feedback/course-feedback",
    heading: "Course Feedback",
    fetchKeys: ["feedback/end-semester-feedback"],
    domain: "erp",
    sourceMode: "erp",
    integrationState: "native",
    renderer: "generic",
    loadingMessage: "Loading course feedback...",
  },
  "/feedback/events-feedback": {
    route: "/feedback/events-feedback",
    heading: "Events Feedback",
    fetchKeys: ["feedback/events-feedback"],
    domain: "campus",
    sourceMode: "external",
    integrationState: "summary",
    renderer: "generic",
    loadingMessage: "Loading events feedback...",
  },
  "/feedback/hostel-mess-feedback": {
    route: "/feedback/hostel-mess-feedback",
    heading: "Hostel & Mess Feedback",
    fetchKeys: ["feedback/hostel-mess-feedback"],
    domain: "campus",
    sourceMode: "external",
    integrationState: "summary",
    renderer: "generic",
    loadingMessage: "Loading hostel and mess feedback...",
  },
  "/feedback/transport-feedback": {
    route: "/feedback/transport-feedback",
    heading: "Transport Feedback",
    fetchKeys: ["feedback/transport-feedback"],
    domain: "campus",
    sourceMode: "external",
    integrationState: "summary",
    renderer: "generic",
    loadingMessage: "Loading transport feedback...",
  },
};
