import type { PageBlueprint } from "../erpBlueprintTypes";

export const WORKSPACE_PAGE_BLUEPRINTS: Record<string, PageBlueprint> = {
  "/resources/learning-materials": {
    route: "/resources/learning-materials",
    heading: "Learning Materials",
    fetchKeys: ["resources/learning-materials"],
    domain: "lms",
    sourceMode: "internal",
    integrationState: "native",
    renderer: "generic",
    loadingMessage: "Loading learning materials...",
  },
  "/resources/advanced-access": {
    route: "/resources/advanced-access",
    heading: "Advanced Access",
    fetchKeys: ["resources/advanced-access"],
    domain: "lms",
    sourceMode: "internal",
    integrationState: "native",
    renderer: "generic",
    loadingMessage: "Loading advanced access...",
  },

  "/academic-tracker/progress-overview": {
    route: "/academic-tracker/progress-overview",
    heading: "Progress Overview",
    fetchKeys: ["academic-tracker/progress-overview"],
    domain: "lms",
    sourceMode: "external",
    integrationState: "summary",
    renderer: "generic",
    loadingMessage: "Loading progress overview...",
  },
  "/academic-tracker/academic-insights": {
    route: "/academic-tracker/academic-insights",
    heading: "Academic Insights",
    fetchKeys: ["academic-tracker/academic-insights"],
    domain: "lms",
    sourceMode: "external",
    integrationState: "summary",
    renderer: "generic",
    loadingMessage: "Loading academic insights...",
  },
  "/academic-tracker/unified-insights": {
    route: "/academic-tracker/unified-insights",
    heading: "Unified Insights",
    fetchKeys: ["academic-tracker/unified-insights"],
    domain: "lms",
    sourceMode: "internal",
    integrationState: "native",
    renderer: "generic",
    loadingMessage: "Loading unified insights...",
  },

  "/career": {
    route: "/career",
    heading: "Career Portal",
    fetchKeys: ["career/opportunities"],
    domain: "career",
    sourceMode: "internal",
    integrationState: "native",
    renderer: "generic",
    loadingMessage: "Opening Career Portal...",
  },
  "/career/opportunities": {
    route: "/career/opportunities",
    heading: "All Opportunities",
    fetchKeys: ["career/opportunities"],
    domain: "career",
    sourceMode: "internal",
    integrationState: "native",
    renderer: "generic",
    loadingMessage: "Searching opportunities...",
  },
  "/career/jobs": {
    route: "/career/jobs",
    heading: "Job Opportunities",
    fetchKeys: ["career/opportunities"],
    domain: "career",
    sourceMode: "internal",
    integrationState: "native",
    renderer: "generic",
    loadingMessage: "Searching jobs...",
  },
  "/career/internships": {
    route: "/career/internships",
    heading: "Internships",
    fetchKeys: ["career/opportunities"],
    domain: "career",
    sourceMode: "internal",
    integrationState: "native",
    renderer: "generic",
    loadingMessage: "Searching internships...",
  },
  "/career/hackathons": {
    route: "/career/hackathons",
    heading: "Hackathons",
    fetchKeys: ["career/opportunities"],
    domain: "career",
    sourceMode: "internal",
    integrationState: "native",
    renderer: "generic",
    loadingMessage: "Searching hackathons...",
  },
  "/career/competitions": {
    route: "/career/competitions",
    heading: "Competitions",
    fetchKeys: ["career/opportunities"],
    domain: "career",
    sourceMode: "internal",
    integrationState: "native",
    renderer: "generic",
    loadingMessage: "Searching competitions...",
  },
  "/career/me/bookmarks": {
    route: "/career/me/bookmarks",
    heading: "My Bookmarks",
    fetchKeys: ["career/opportunities"],
    domain: "career",
    sourceMode: "internal",
    integrationState: "native",
    renderer: "generic",
    loadingMessage: "Loading bookmarks...",
  },
  "/career/me/profile": {
    route: "/career/me/profile",
    heading: "Career Profile",
    fetchKeys: ["career/profile"],
    domain: "career",
    sourceMode: "internal",
    integrationState: "native",
    renderer: "generic",
    loadingMessage: "Loading profile...",
  },
  "/career/me/skill-gap": {
    route: "/career/me/skill-gap",
    heading: "Skill Gap Analysis",
    fetchKeys: ["career/profile/skill-gaps"],
    domain: "career",
    sourceMode: "internal",
    integrationState: "native",
    renderer: "generic",
    loadingMessage: "Analyzing skill gaps...",
  },
  "/career/me/tracker": {
    route: "/career/me/tracker",
    heading: "Application Tracker",
    fetchKeys: ["career/applications"],
    domain: "career",
    sourceMode: "internal",
    integrationState: "native",
    renderer: "generic",
    loadingMessage: "Loading application tracker...",
  },
  "/career/submit": {
    route: "/career/submit",
    heading: "Submit Opportunity",
    fetchKeys: [],
    domain: "career",
    sourceMode: "internal",
    integrationState: "native",
    renderer: "generic",
    loadingMessage: "Opening submission form...",
  },
  "/career/alumni": {
    route: "/career/alumni",
    heading: "Alumni Connect",
    fetchKeys: ["career/alumni"],
    domain: "career",
    sourceMode: "internal",
    integrationState: "native",
    renderer: "generic",
    loadingMessage: "Loading alumni...",
  },
  "/career/interviews": {
    route: "/career/interviews",
    heading: "Interview Booking",
    fetchKeys: ["career/interviews"],
    domain: "career",
    sourceMode: "internal",
    integrationState: "native",
    renderer: "generic",
    loadingMessage: "Loading interviews...",
  },
  "/career/me/resume": {
    route: "/career/me/resume",
    heading: "Resume Builder",
    fetchKeys: ["career/resume"],
    domain: "career",
    sourceMode: "internal",
    integrationState: "native",
    renderer: "generic",
    loadingMessage: "Loading resume...",
  },
  "/career/opportunities/:id": {
    route: "/career/opportunities/:id",
    heading: "Opportunity Details",
    fetchKeys: ["career/opportunities/:id"],
    domain: "career",
    sourceMode: "internal",
    integrationState: "native",
    renderer: "generic",
    loadingMessage: "Loading details...",
  },

  "/helpdesk/raise-ticket": {
    route: "/helpdesk/raise-ticket",
    heading: "Raise a Ticket",
    fetchKeys: ["helpdesk/raise-ticket"],
    domain: "campus",
    sourceMode: "external",
    integrationState: "summary",
    renderer: "generic",
    loadingMessage: "Loading ticket desk...",
  },
  "/helpdesk/faqs": {
    route: "/helpdesk/faqs",
    heading: "FAQs",
    fetchKeys: ["helpdesk/faqs"],
    domain: "campus",
    sourceMode: "external",
    integrationState: "summary",
    renderer: "generic",
    loadingMessage: "Loading helpdesk FAQs...",
  },
  "/helpdesk/track-escalate": {
    route: "/helpdesk/track-escalate",
    heading: "Track & Escalate",
    fetchKeys: ["helpdesk/track-escalate"],
    domain: "campus",
    sourceMode: "external",
    integrationState: "summary",
    renderer: "generic",
    loadingMessage: "Loading escalations...",
  },

  "/notifications": {
    route: "/notifications",
    heading: "Notifications",
    fetchKeys: ["announcements"],
    domain: "erp",
    sourceMode: "erp",
    integrationState: "native",
    renderer: "announcements",
    loadingMessage: "Loading notifications...",
  },
  "/settings": {
    route: "/settings",
    heading: "Settings",
    fetchKeys: ["verification/mobile-no-verification"],
    domain: "erp",
    sourceMode: "erp",
    integrationState: "native",
    renderer: "document",
    loadingMessage: "Loading settings...",
  },
  "/profile": {
    route: "/profile",
    heading: "Profile",
    fetchKeys: ["profile", "verification/mobile-no-verification"],
    domain: "erp",
    sourceMode: "erp",
    integrationState: "native",
    renderer: "profile",
    includeSessionProfile: true,
    loadingMessage: "Loading profile...",
  },
  "/admin/events-management": {
    route: "/admin/events-management",
    heading: "Admin Events Management",
    fetchKeys: [],
    domain: "admin",
    sourceMode: "internal",
    integrationState: "native",
    renderer: "generic",
    loadingMessage: "Loading events management...",
  },
  "/admin/content-management": {
    route: "/admin/content-management",
    heading: "Admin Content Management",
    fetchKeys: [],
    domain: "admin",
    sourceMode: "internal",
    integrationState: "native",
    renderer: "generic",
    loadingMessage: "Loading content management...",
  },
  "/admin/campus-feedback": {
    route: "/admin/campus-feedback",
    heading: "Campus Feedback Moderation",
    fetchKeys: [],
    domain: "admin",
    sourceMode: "internal",
    integrationState: "native",
    renderer: "generic",
    loadingMessage: "Loading campus feedback...",
  },
  "/admin/lms-moderation": {
    route: "/admin/lms-moderation",
    heading: "LMS Moderation",
    fetchKeys: [],
    domain: "admin",
    sourceMode: "internal",
    integrationState: "native",
    renderer: "generic",
    loadingMessage: "Loading LMS moderation...",
  },
  "/admin/system-controls": {
    route: "/admin/system-controls",
    heading: "Admin System Controls",
    fetchKeys: [],
    domain: "admin",
    sourceMode: "internal",
    integrationState: "native",
    renderer: "generic",
    loadingMessage: "Loading system controls...",
  },
  "/admin/helpdesk-tickets": {
    route: "/admin/helpdesk-tickets",
    heading: "Admin Helpdesk Tickets",
    fetchKeys: [],
    domain: "admin",
    sourceMode: "internal",
    integrationState: "native",
    renderer: "generic",
    loadingMessage: "Loading helpdesk tickets...",
  },
  "/admin/helpdesk-faqs": {
    route: "/admin/helpdesk-faqs",
    heading: "Admin Helpdesk FAQs",
    fetchKeys: [],
    domain: "admin",
    sourceMode: "internal",
    integrationState: "native",
    renderer: "generic",
    loadingMessage: "Loading helpdesk FAQs...",
  },
  "/admin/career-opportunities": {
    route: "/admin/career-opportunities",
    heading: "Admin Career Opportunities",
    fetchKeys: [],
    domain: "admin",
    sourceMode: "internal",
    integrationState: "native",
    renderer: "generic",
    loadingMessage: "Loading career opportunities...",
  },
  "/admin/career-interviews": {
    route: "/admin/career-interviews",
    heading: "Admin Career Interviews",
    fetchKeys: [],
    domain: "admin",
    sourceMode: "internal",
    integrationState: "native",
    renderer: "generic",
    loadingMessage: "Loading career interviews...",
  },
  "/admin/career-alumni": {
    route: "/admin/career-alumni",
    heading: "Admin Career Alumni",
    fetchKeys: [],
    domain: "admin",
    sourceMode: "internal",
    integrationState: "native",
    renderer: "generic",
    loadingMessage: "Loading alumni management...",
  },
  "/admin/department-performance": {
    route: "/admin/department-performance",
    heading: "Department Performance",
    fetchKeys: [],
    domain: "admin",
    sourceMode: "internal",
    integrationState: "native",
    renderer: "generic",
    loadingMessage: "Loading department performance...",
  },
  "/admin/event-approvals": {
    route: "/admin/event-approvals",
    heading: "Event Approvals",
    fetchKeys: [],
    domain: "admin",
    sourceMode: "internal",
    integrationState: "native",
    renderer: "generic",
    loadingMessage: "Loading event approvals...",
  },
  "/admin/audit-logs": {
    route: "/admin/audit-logs",
    heading: "System Audit Logs",
    fetchKeys: [],
    domain: "admin",
    sourceMode: "internal",
    integrationState: "native",
    renderer: "generic",
    loadingMessage: "Loading audit logs...",
  },
  "/admin/certificate-templates": {
    route: "/admin/certificate-templates",
    heading: "Certificate Templates",
    fetchKeys: [],
    domain: "admin",
    sourceMode: "internal",
    integrationState: "native",
    renderer: "generic",
    loadingMessage: "Loading certificate templates...",
  },
};
