"use strict";

/**
 * Canonical skill-name formatting.
 *
 * Skills arrive from three noisy sources — resume parsing, opportunity-listing
 * keyword extraction (lowercased), and free-text profile entry — and were being
 * rendered through a CSS `text-transform: capitalize`, which mangles acronyms
 * ("aws" -> "Aws") and dotted names ("node.js" -> "Node.Js"). Canonicalise once,
 * on write, so every surface can render the string verbatim.
 */

// Canonical spellings we always want, keyed by their squashed lowercase form
// (letters + digits only, so "node.js", "node js" and "nodejs" all collide).
const CANONICAL = [
  "JavaScript",
  "TypeScript",
  "Python",
  "Java",
  "Kotlin",
  "Swift",
  "Go",
  "Rust",
  "Ruby",
  "PHP",
  "Scala",
  "C",
  "C++",
  "C#",
  "R",
  "MATLAB",
  "SQL",
  "NoSQL",
  "HTML",
  "CSS",
  "Sass",
  "React",
  "React Native",
  "Next.js",
  "Vue.js",
  "Angular",
  "Svelte",
  "Node.js",
  "Express.js",
  "Django",
  "Flask",
  "FastAPI",
  "Spring Boot",
  ".NET",
  "Tailwind CSS",
  "Redux",
  "GraphQL",
  "REST API",
  "gRPC",
  "WebSockets",
  "PostgreSQL",
  "MySQL",
  "SQLite",
  "MongoDB",
  "Redis",
  "Elasticsearch",
  "Firebase",
  "Supabase",
  "AWS",
  "Azure",
  "GCP",
  "Docker",
  "Kubernetes",
  "Terraform",
  "Ansible",
  "Linux",
  "Bash",
  "Git",
  "GitHub Actions",
  "CI/CD",
  "Nginx",
  "Kafka",
  "RabbitMQ",
  "Machine Learning",
  "Deep Learning",
  "NLP",
  "Computer Vision",
  "Data Analysis",
  "Data Science",
  "Data Engineering",
  "Pandas",
  "NumPy",
  "scikit-learn",
  "TensorFlow",
  "PyTorch",
  "Keras",
  "OpenCV",
  "YOLO",
  "CLIP",
  "FAISS",
  "ArUco",
  "MediaPipe",
  "Hugging Face",
  "Transformers",
  "LangChain",
  "ONNX Runtime",
  "SUMO",
  "ROS",
  "CUDA",
  "Power BI",
  "Tableau",
  "Excel",
  "Figma",
  "UI/UX Design",
  "System Design",
  "Data Structures",
  "Algorithms",
  "OOP",
  "DevOps",
  "Agile",
  "Scrum",
  "Cybersecurity",
  "Penetration Testing",
  "Blockchain",
  "Solidity",
  "Android",
  "iOS",
  "Flutter",
  "Unity",
  "Embedded Systems",
  "Arduino",
  "IoT",
  "VLSI",
  "MERN Stack",
  "Communication",
  "Leadership",
  "Problem Solving",
  "Public Speaking",
  "Project Management",
  // ── Languages / low level ────────────────────────────────────────────────
  "Objective-C",
  "Dart",
  "Perl",
  "Lua",
  "Haskell",
  "Elixir",
  "Clojure",
  "Julia",
  "Assembly",
  "Verilog",
  "SystemVerilog",
  "VHDL",
  "Solidity",
  "Groovy",
  "Shell Scripting",
  "PowerShell",
  "PL/SQL",
  "T-SQL",
  // ── Web / frontend ──────────────────────────────────────────────────────
  "JavaScript (ES6+)",
  "jQuery",
  "Bootstrap",
  "Material UI",
  "Chakra UI",
  "Webpack",
  "Vite",
  "Babel",
  "Three.js",
  "D3.js",
  "WebGL",
  "WebRTC",
  "Progressive Web Apps",
  "Server-Side Rendering",
  "Accessibility",
  "Responsive Design",
  "Nuxt.js",
  "Remix",
  "Astro",
  "Zustand",
  "React Query",
  "Redux Toolkit",
  "Storybook",
  // ── Backend / APIs ─────────────────────────────────────────────────────
  "Spring",
  "Hibernate",
  "NestJS",
  "Ruby on Rails",
  "Laravel",
  "ASP.NET Core",
  "Gin",
  "Fiber",
  "Ktor",
  "Micronaut",
  "Socket.IO",
  "OpenAPI",
  "Swagger",
  "OAuth",
  "JWT",
  "Microservices",
  "Serverless",
  "Message Queues",
  // ── Databases / data ──────────────────────────────────────────────────
  "MariaDB",
  "Oracle Database",
  "SQL Server",
  "DynamoDB",
  "Cassandra",
  "Neo4j",
  "CouchDB",
  "InfluxDB",
  "Snowflake",
  "BigQuery",
  "Redshift",
  "Databricks",
  "Apache Spark",
  "Hadoop",
  "Airflow",
  "dbt",
  "ETL",
  "Data Warehousing",
  "Data Modeling",
  "Prisma",
  "SQLAlchemy",
  "Sequelize",
  "TypeORM",
  "Drizzle",
  // ── Cloud / infra / devops ───────────────────────────────────────────
  "AWS Lambda",
  "AWS EC2",
  "AWS S3",
  "Amazon RDS",
  "CloudFormation",
  "Google Cloud Platform",
  "Vercel",
  "Netlify",
  "Heroku",
  "DigitalOcean",
  "Cloudflare",
  "Prometheus",
  "Grafana",
  "ELK Stack",
  "Datadog",
  "Sentry",
  "Jenkins",
  "GitLab CI",
  "CircleCI",
  "Travis CI",
  "ArgoCD",
  "Helm",
  "Istio",
  "Podman",
  "Vagrant",
  "Load Balancing",
  "Infrastructure as Code",
  "Site Reliability Engineering",
  // ── AI / ML ──────────────────────────────────────────────────────────
  "LLMs",
  "Generative AI",
  "Prompt Engineering",
  "RAG",
  "Fine-tuning",
  "LlamaIndex",
  "OpenAI API",
  "Anthropic API",
  "Ollama",
  "vLLM",
  "Vector Databases",
  "Pinecone",
  "ChromaDB",
  "Weaviate",
  "Sentence Transformers",
  "XGBoost",
  "LightGBM",
  "Matplotlib",
  "Seaborn",
  "Plotly",
  "SciPy",
  "NLTK",
  "spaCy",
  "Reinforcement Learning",
  "Supervised Learning",
  "Unsupervised Learning",
  "Feature Engineering",
  "Model Deployment",
  "MLOps",
  "MLflow",
  "Weights & Biases",
  "Kaggle",
  "Time Series Analysis",
  "Recommendation Systems",
  "Statistical Modeling",
  "A/B Testing",
  "Object Detection",
  "Image Segmentation",
  "OCR",
  "Speech Recognition",
  "Diffusion Models",
  "GANs",
  "Transformers Architecture",
  // ── Systems / embedded / robotics ───────────────────────────────────
  "RTOS",
  "FreeRTOS",
  "Zephyr",
  "Embedded C",
  "Firmware Development",
  "Device Drivers",
  "Linux Kernel",
  "Microcontrollers",
  "STM32",
  "ESP32",
  "Raspberry Pi",
  "FPGA",
  "PCB Design",
  "SPICE",
  "Altium Designer",
  "KiCad",
  "CAN Bus",
  "I2C",
  "SPI",
  "UART",
  "ROS2",
  "Gazebo",
  "SLAM",
  "Motion Planning",
  "Control Systems",
  "Digital Signal Processing",
  "Computer Architecture",
  "Operating Systems",
  "Networking",
  "TCP/IP",
  "Compilers",
  "Distributed Systems",
  "Concurrency",
  "Multithreading",
  "Parallel Computing",
  "Memory Management",
  // ── Mobile / game ───────────────────────────────────────────────────
  "Jetpack Compose",
  "SwiftUI",
  "Kotlin Multiplatform",
  "Expo",
  "Unreal Engine",
  "Godot",
  "Blender",
  // ── Practices / CS fundamentals ─────────────────────────────────────
  "Object-Oriented Programming",
  "Functional Programming",
  "Design Patterns",
  "Test-Driven Development",
  "Unit Testing",
  "Integration Testing",
  "Jest",
  "Vitest",
  "Pytest",
  "Cypress",
  "Playwright",
  "Selenium",
  "JUnit",
  "Mocha",
  "Code Review",
  "Pair Programming",
  "Version Control",
  "Debugging",
  "Performance Optimization",
  "Software Architecture",
  "Domain-Driven Design",
  "Event-Driven Architecture",
  "Kanban",
  "JIRA",
  "Confluence",
  "Notion",
  "Postman",
  "GDB",
  "Valgrind",
  "Wireshark",
  "Nmap",
  "Burp Suite",
  "Metasploit",
  "OWASP",
  "Cryptography",
  "Network Security",
  "Ethical Hacking",
  "Digital Forensics",
  // ── Data viz / office / design ──────────────────────────────────────
  "Looker",
  "Metabase",
  "Google Analytics",
  "Adobe XD",
  "Sketch",
  "Canva",
  "LaTeX",
  "Markdown",
  "Technical Writing",
  "Teamwork",
  "Time Management",
  "Critical Thinking",
  "Mentoring",
  "Agile Methodologies",
];

const CANONICAL_BY_KEY = new Map();
for (const name of CANONICAL) {
  CANONICAL_BY_KEY.set(squash(name), name);
}

// Explicit aliases -> canonical key (also squashed on lookup).
const ALIASES = {
  js: "JavaScript",
  ts: "TypeScript",
  golang: "Go",
  py: "Python",
  "c plus plus": "C++",
  cpp: "C++",
  "c sharp": "C#",
  csharp: "C#",
  dotnet: ".NET",
  "asp net": ".NET",
  node: "Node.js",
  nodejs: "Node.js",
  "node js": "Node.js",
  express: "Express.js",
  expressjs: "Express.js",
  reactjs: "React",
  "react.js": "React",
  nextjs: "Next.js",
  vue: "Vue.js",
  vuejs: "Vue.js",
  ng: "Angular",
  rn: "React Native",
  tailwind: "Tailwind CSS",
  tailwindcss: "Tailwind CSS",
  postgres: "PostgreSQL",
  psql: "PostgreSQL",
  mongo: "MongoDB",
  es: "Elasticsearch",
  k8s: "Kubernetes",
  "amazon web services": "AWS",
  "google cloud": "GCP",
  "google cloud platform": "GCP",
  gcloud: "GCP",
  ml: "Machine Learning",
  dl: "Deep Learning",
  "natural language processing": "NLP",
  cv: "Computer Vision",
  ds: "Data Structures",
  dsa: "Data Structures",
  "data structures and algorithms": "Data Structures",
  "object oriented programming": "OOP",
  oops: "OOP",
  restful: "REST API",
  rest: "REST API",
  "rest apis": "REST API",
  api: "REST API",
  cicd: "CI/CD",
  "ci cd": "CI/CD",
  sklearn: "scikit-learn",
  "scikit learn": "scikit-learn",
  tf: "TensorFlow",
  pytorch: "PyTorch",
  huggingface: "Hugging Face",
  hf: "Hugging Face",
  langchain: "LangChain",
  onnx: "ONNX Runtime",
  onnxruntime: "ONNX Runtime",
  "ort": "ONNX Runtime",
  "opencv": "OpenCV",
  "ros2": "ROS",
  powerbi: "Power BI",
  "ui ux": "UI/UX Design",
  uiux: "UI/UX Design",
  "ui/ux": "UI/UX Design",
  "system designs": "System Design",
  mern: "MERN Stack",
  oop: "OOP",
  "oop concepts": "OOP",
  "oo programming": "OOP",
  "functional programming": "Functional Programming",
  "object oriented": "OOP",
  os: "Operating Systems",
  dbms: "Databases",
  "database management": "Databases",
  rdbms: "Databases",
  os: "Operating Systems",
  cn: "Networking",
  "computer networks": "Networking",
  "comp networks": "Networking",
  "operating system": "Operating Systems",
  "comp architecture": "Computer Architecture",
  tdd: "Test-Driven Development",
  bdd: "Test-Driven Development",
  "gen ai": "Generative AI",
  genai: "Generative AI",
  "llm": "LLMs",
  llms: "LLMs",
  "large language models": "LLMs",
  "prompt engg": "Prompt Engineering",
  rag: "RAG",
  "retrieval augmented generation": "RAG",
  "vector db": "Vector Databases",
  "vector stores": "Vector Databases",
  "vector store": "Vector Databases",
  rl: "Reinforcement Learning",
  "reinforcement learning": "Reinforcement Learning",
  numpy: "NumPy",
  pandas: "Pandas",
  matplotlib: "Matplotlib",
  hdl: "Verilog",
  "verilog hdl": "Verilog",
  "system verilog": "SystemVerilog",
  rtos: "RTOS",
  freertos: "FreeRTOS",
  "embedded c": "Embedded C",
  "device drivers": "Device Drivers",
  "linux kernel": "Linux Kernel",
  dsp: "Digital Signal Processing",
  "tcp ip": "TCP/IP",
  "tcp/ip": "TCP/IP",
  "distributed systems": "Distributed Systems",
  ros: "ROS",
  "restful apis": "REST API",
  "rest api": "REST API",
  gcc: "GCC",
  make: "Make",
  cmake: "CMake",
  "gnu make": "Make",
  xampp: "XAMPP",
  postman: "Postman",
  "rest assured": "REST Assured",
  bootstrap: "Bootstrap",
  jquery: "jQuery",
  "material ui": "Material UI",
  mui: "Material UI",
  "tailwind css": "Tailwind CSS",
  "spring boot": "Spring Boot",
  springboot: "Spring Boot",
  "ruby on rails": "Ruby on Rails",
  rails: "Ruby on Rails",
  "asp.net": "ASP.NET Core",
  "asp.net core": "ASP.NET Core",
  ejs: "EJS",
  "socket io": "Socket.IO",
  socketio: "Socket.IO",
  websocket: "WebSockets",
  websockets: "WebSockets",
  graphql: "GraphQL",
  "d3": "D3.js",
  "d3js": "D3.js",
  threejs: "Three.js",
  "three js": "Three.js",
  "next js": "Next.js",
  "nuxt": "Nuxt.js",
  "gatsby": "Gatsby",
  webpack: "Webpack",
  vite: "Vite",
  babel: "Babel",
  eslint: "ESLint",
  prettier: "Prettier",
  npm: "npm",
  yarn: "Yarn",
  pnpm: "pnpm",
  jira: "JIRA",
  "google analytics": "Google Analytics",
  ga: "Google Analytics",
  latex: "LaTeX",
  markdown: "Markdown",
  "adobe xd": "Adobe XD",
  xd: "Adobe XD",
  sketch: "Sketch",
  canva: "Canva",
  "power bi": "Power BI",
  tableau: "Tableau",
  looker: "Looker",
  metabase: "Metabase",
  "aws lambda": "AWS Lambda",
  lambda: "AWS Lambda",
  ec2: "AWS EC2",
  s3: "AWS S3",
  rds: "Amazon RDS",
  cloudformation: "CloudFormation",
  terraform: "Terraform",
  ansible: "Ansible",
  jenkins: "Jenkins",
  "gitlab ci": "GitLab CI",
  "github actions": "GitHub Actions",
  circleci: "CircleCI",
  "travis ci": "Travis CI",
  travis: "Travis CI",
  prometheus: "Prometheus",
  grafana: "Grafana",
  "elk stack": "ELK Stack",
  elk: "ELK Stack",
  datadog: "Datadog",
  sentry: "Sentry",
  helm: "Helm",
  istio: "Istio",
  podman: "Podman",
  spark: "Apache Spark",
  "apache spark": "Apache Spark",
  "pyspark": "Apache Spark",
  hadoop: "Hadoop",
  airflow: "Airflow",
  kafka: "Kafka",
  rabbitmq: "RabbitMQ",
  snowflake: "Snowflake",
  bigquery: "BigQuery",
  redshift: "Redshift",
  databricks: "Databricks",
  "etl": "ETL",
  "elt": "ETL",
  "data warehousing": "Data Warehousing",
  prisma: "Prisma",
  sqlalchemy: "SQLAlchemy",
  sequelize: "Sequelize",
  typeorm: "TypeORM",
  hibernate: "Hibernate",
  mariadb: "MariaDB",
  "sql server": "SQL Server",
  mssql: "SQL Server",
  dynamodb: "DynamoDB",
  cassandra: "Cassandra",
  neo4j: "Neo4j",
  influxdb: "InfluxDB",
  "plsql": "PL/SQL",
  "pl sql": "PL/SQL",
  "t sql": "T-SQL",
  xgboost: "XGBoost",
  lightgbm: "LightGBM",
  seaborn: "Seaborn",
  plotly: "Plotly",
  scipy: "SciPy",
  nltk: "NLTK",
  spacy: "spaCy",
  mlflow: "MLflow",
  "wandb": "Weights & Biases",
  "weights and biases": "Weights & Biases",
  kaggle: "Kaggle",
  "openai api": "OpenAI API",
  openai: "OpenAI API",
  "anthropic api": "Anthropic API",
  ollama: "Ollama",
  vllm: "vLLM",
  pinecone: "Pinecone",
  chromadb: "ChromaDB",
  chroma: "ChromaDB",
  weaviate: "Weaviate",
  "sentence transformers": "Sentence Transformers",
  llamaindex: "LlamaIndex",
  "llama index": "LlamaIndex",
  "object detection": "Object Detection",
  "image segmentation": "Image Segmentation",
  ocr: "OCR",
  gan: "GANs",
  gans: "GANs",
  jest: "Jest",
  vitest: "Vitest",
  pytest: "Pytest",
  cypress: "Cypress",
  selenium: "Selenium",
  junit: "JUnit",
  mocha: "Mocha",
  chai: "Chai",
  gdb: "GDB",
  valgrind: "Valgrind",
  wireshark: "Wireshark",
  nmap: "Nmap",
  "burp suite": "Burp Suite",
  metasploit: "Metasploit",
  owasp: "OWASP",
  "jetpack compose": "Jetpack Compose",
  swiftui: "SwiftUI",
  expo: "Expo",
  "unreal engine": "Unreal Engine",
  unreal: "Unreal Engine",
  godot: "Godot",
  blender: "Blender",
  "objective c": "Objective-C",
  objc: "Objective-C",
  golang2: "Go",
  dart: "Dart",
  perl: "Perl",
  lua: "Lua",
  haskell: "Haskell",
  elixir: "Elixir",
  clojure: "Clojure",
  julia: "Julia",
  assembly: "Assembly",
  asm: "Assembly",
  x86: "Assembly",
  arm: "ARM",
  fpga: "FPGA",
  vhdl: "VHDL",
  "pcb design": "PCB Design",
  altium: "Altium Designer",
  kicad: "KiCad",
  spice: "SPICE",
  "stm32": "STM32",
  esp32: "ESP32",
  "raspberry pi": "Raspberry Pi",
  arduino: "Arduino",
  "can bus": "CAN Bus",
  i2c: "I2C",
  spi: "SPI",
  uart: "UART",
  gazebo: "Gazebo",
  slam: "SLAM",
  "motion planning": "Motion Planning",
  "control systems": "Control Systems",
  "powershell": "PowerShell",
  "shell scripting": "Shell Scripting",
  "shell": "Shell Scripting",
  "bash scripting": "Bash",
  "design patterns": "Design Patterns",
  "unit testing": "Unit Testing",
  "integration testing": "Integration Testing",
  microservices: "Microservices",
  serverless: "Serverless",
  oauth: "OAuth",
  jwt: "JWT",
  swagger: "Swagger",
  openapi: "OpenAPI",
  agile: "Agile",
  scrum: "Scrum",
  kanban: "Kanban",
  "agile methodologies": "Agile",
  "problem-solving": "Problem Solving",
  "problem solving": "Problem Solving",
  teamwork: "Teamwork",
  "team work": "Teamwork",
  "critical thinking": "Critical Thinking",
  "time management": "Time Management",
  "technical writing": "Technical Writing",
  mentoring: "Mentoring",
  "public speaking": "Public Speaking",
  "cyber security": "Cybersecurity",
  cybersecurity: "Cybersecurity",
  "pen testing": "Penetration Testing",
  "penetration testing": "Penetration Testing",
  cryptography: "Cryptography",
  "network security": "Network Security",
  "ethical hacking": "Ethical Hacking",
  blockchain: "Blockchain",
  solidity: "Solidity",
  web3: "Web3",
  ethereum: "Ethereum",
  flutter: "Flutter",
  "react native": "React Native",
  android: "Android",
  ios: "iOS",
  kotlin: "Kotlin",
  swift: "Swift",
  unity: "Unity",
  "a b testing": "A/B Testing",
  "a/b testing": "A/B Testing",
  "time series": "Time Series Analysis",
  "recommendation systems": "Recommendation Systems",
  "feature engineering": "Feature Engineering",
  "model deployment": "Model Deployment",
  mlops: "MLOps",
  "fine tuning": "Fine-tuning",
  finetuning: "Fine-tuning",
  "agentic workflows": "Agentic Workflows",
  "agentic ai": "Agentic Workflows",
};

const ALIAS_BY_KEY = new Map();
for (const [alias, canonical] of Object.entries(ALIASES)) {
  ALIAS_BY_KEY.set(squash(alias), canonical);
}

// Broad recognition set — a cleaned public skill vocabulary (see
// data/skills.NOTICE.md). This only widens what counts as "a skill"; the
// curated CANONICAL / ALIASES tables above still own display casing.
const VENDORED_SKILL_KEYS = new Set();
try {
  // squash() is defined below; it is hoisted as a function declaration.
  for (const s of require("../data/skills.json")) {
    const k = squash(s);
    if (k) VENDORED_SKILL_KEYS.add(k);
  }
} catch {
  /* list is optional — recognition just falls back to the curated set */
}

// Tokens that should render upper-cased when we fall through to title-casing.
const ACRONYMS = new Set([
  "ai",
  "ml",
  "ar",
  "vr",
  "xr",
  "os",
  "db",
  "ui",
  "ux",
  "qa",
  "sre",
  "etl",
  "elt",
  "orm",
  "jwt",
  "seo",
  "sdk",
  "api",
  "cli",
  "gui",
  "sql",
  "css",
  "html",
  "php",
  "aws",
  "gcp",
  "iot",
  "cdn",
  "dns",
  "tcp",
  "udp",
  "ssh",
  "ssl",
  "tls",
]);

function squash(value) {
  // Keep "+" and "#" so "C", "C++" and "C#" stay distinct.
  return String(value || "").toLowerCase().replace(/[^a-z0-9+#]+/g, "");
}

function titleCaseToken(token) {
  if (!token) return token;
  if (ACRONYMS.has(token.toLowerCase())) return token.toUpperCase();
  // Keep tokens that already carry meaningful internal caps (e.g. "iOS").
  if (/[a-z][A-Z]/.test(token)) return token;
  return token.charAt(0).toUpperCase() + token.slice(1).toLowerCase();
}

/**
 * Normalise one raw skill string to its canonical display form.
 * Returns "" for empty/whitespace input.
 */
function canonicalizeSkill(raw) {
  const trimmed = String(raw || "").trim().replace(/\s+/g, " ");
  if (!trimmed) return "";

  const key = squash(trimmed);
  if (!key) return trimmed.slice(0, 80);

  if (CANONICAL_BY_KEY.has(key)) return CANONICAL_BY_KEY.get(key);
  if (ALIAS_BY_KEY.has(key)) return ALIAS_BY_KEY.get(key);

  // Known to the vendored list but with no curated casing: title-case it.
  // Fall through anyway to the formatter below for consistent handling.

  // Fall through: title-case each word, preserving separators like "/" and "-".
  const formatted = trimmed
    .split(/(\s+|\/|\+)/)
    .map((part) => (/^\s+$|^[/+]$/.test(part) ? part : titleCaseToken(part)))
    .join("");
  return formatted.slice(0, 80);
}

/** True when the raw token maps to a known skill (curated or vendored list). */
function isKnownSkill(raw) {
  const key = squash(raw);
  return (
    Boolean(key) &&
    (CANONICAL_BY_KEY.has(key) || ALIAS_BY_KEY.has(key) || VENDORED_SKILL_KEYS.has(key))
  );
}

/**
 * Canonicalise a list, dropping blanks and case-insensitive duplicates while
 * preserving first-seen order.
 */
function canonicalizeSkills(list) {
  const seen = new Set();
  const out = [];
  for (const item of Array.isArray(list) ? list : []) {
    const canonical = canonicalizeSkill(item);
    if (!canonical) continue;
    const dedupeKey = canonical.toLowerCase();
    if (seen.has(dedupeKey)) continue;
    seen.add(dedupeKey);
    out.push(canonical);
  }
  return out;
}

module.exports = {
  canonicalizeSkill,
  canonicalizeSkills,
  isKnownSkill,
  CANONICAL_SKILLS: CANONICAL,
};
